1. Создать вектор размером 10 состоящий из единиц

In [5]:
import numpy as np
n=10
x = np.ones(n)
print('x:', x)

x: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


2. Создать массив 4x4 заполненный случайными числами от 0 до 1

In [30]:
n=4
x = np.random.sample((n, n))
print('x:\n', x)

x:
 [[0.88261549 0.6164385  0.68218996 0.2193748 ]
 [0.12070229 0.12009045 0.00200559 0.99051776]
 [0.51707593 0.57674043 0.09595395 0.77862414]
 [0.36187148 0.44847571 0.71696373 0.94429663]]


3. Создать массив 5x3 заполненный случайными целыми числами от 0 до 100

In [7]:
f = np.random.randint(0, 100, (5, 3))
print('f:\n', f)

f:
 [[60 22 68]
 [78 70  1]
 [83 34 55]
 [ 0  0 76]
 [78 50 89]]


4. Поменять форму предыдущего массива на 3х5, а тип на float

In [15]:
f.shape = (3, 5)
f.dtype = float
print('f:\n', f)

f:
 [[2.96e-322 1.09e-322 3.36e-322 3.85e-322 3.46e-322]
 [4.94e-324 4.10e-322 1.68e-322 2.72e-322 0.00e+000]
 [0.00e+000 3.75e-322 3.85e-322 2.47e-322 4.40e-322]]


5. Найти сумму, максимум и среднее значение массива из пункта 3

In [17]:
f.shape = (5,3)
f.dtype = int
print(np.sum(f))
print(np.max(f))
print(np.sum(f)/np.average(f))

764
89
15.000000000000002


6. Создать функцию который меняет элементы массива на следующее выражение: sin(x)+cos(x)

In [31]:
def sincos(x):
    return np.sin(x) + np.cos(x)
x=sincos(x)
print('x:\n', x)

x:
 [[1.40753581 1.3940755  1.40668819 1.19365315]
 [1.11313373 1.11259981 1.00200358 1.38456688]
 [1.36360883 1.38353905 1.09120672 1.41418112]
 [1.28926104 1.33470156 1.41090328 1.39639755]]


7. Создать функцию вычисляющий: a*b+c, где a,b,c - массивы с размером nxn

In [41]:
def abc(a,b,c):
    return a*b+с

8. Найти определитель матрицы 3x3, если определитель положительный, то найти QR разложение иначе найти обратную матрицу.

In [37]:
n=3
x = np.random.sample((n, n))
print('x:\n', x)
if np.linalg.det(x) > 0:
    a = np.linalg.qr(x)
else:
    a = np.linalg.inv(x)
print('a:\n', a)

x:
 [[0.50888207 0.94545474 0.10815731]
 [0.9897366  0.23923202 0.14436449]
 [0.36272832 0.85769077 0.88004276]]
a:
 [[-0.13393478  1.14184884 -0.17085125]
 [ 1.26444051 -0.63111364 -0.0518703 ]
 [-1.17712122  0.14444688  1.25728125]]


9. Сделать скалярное и матричное умножение двух матриц nxm

In [40]:
x1 = 3
n = np.random.sample((x1, x1))
m = np.random.sample((x1, x1))
a1 = n*m
a2 = n@m
print('a1:\n', a1)
print('a2:\n', a2)

a1:
 [[0.20313051 0.65740571 0.61241291]
 [0.0827167  0.1029918  0.51520313]
 [0.15451968 0.00116571 0.17958578]]
a2:
 [[0.60558177 1.17455269 1.83309388]
 [0.25694981 0.35491704 0.74660301]
 [0.24512717 0.77360377 0.83782526]]


10. Решить систему линейный уравнений Ax = b, где А(nxn) и b(n) задаются случайно.

In [43]:
n=5
A = np.random.sample((n, n))
b = np.random.sample(n)
x = np.linalg.solve(A, b)
print('x:\n', x)

x:
 [-2.86943139  1.23747564  0.69271268 -1.02565684  0.6073001 ]
